

## Add KEGG pathways

```{r}

# Initialize variables to store the last KEGG ID and its corresponding pathway
last_kegg_id <- ""
last_pathway_info <- NA

# Define the function to fetch KEGG pathway names based on the position relative to "09100 Metabolism"
get_kegg_pathway_name <- function(kegg_id) {
  # Handle NA KEGG IDs
  if (is.na(kegg_id)) {
    return(NA)
  }

  if (kegg_id == last_kegg_id) {
    return(last_pathway_info)
  }

  tryCatch({
    brite_info <- keggGet(kegg_id)

    if ("BRITE" %in% names(brite_info[[1]])) {
      brite_section <- brite_info[[1]]$BRITE
      metabolism_index <- which(grepl("09100 Metabolism", brite_section))
      
      if (length(metabolism_index) > 0 && metabolism_index < length(brite_section)) {
        # Extract the pathway information and remove numerical prefix
        pathway_info <- brite_section[metabolism_index + 1]
        pathway_info <- sub("^[0-9]+[[:space:]]+", "", pathway_info)
        
        # Store in global variables for reuse
        last_kegg_id <<- kegg_id
        last_pathway_info <<- pathway_info
        
        return(pathway_info)
      }
    }

    # Store NA for this KEGG ID and return NA
    last_kegg_id <<- kegg_id
    last_pathway_info <<- NA
    return(NA)
  }, error = function(e) {
    # In case of an error, store NA for this KEGG ID and return NA
    last_kegg_id <<- kegg_id
    last_pathway_info <<- NA
    return(NA)
  })
}

# Apply the function to the entire dataset
data_augmented <- data_augmented |> 
  mutate(Pathway_Info = map_chr(KEGG_Orthology, get_kegg_pathway_name))

```


## Save cleaned data

```{r}

# Define the path for the output .tsv file
output_file_path <- "../data/data_augmented.tsv"

# Save the subset data frame to a .tsv file
write.table(data_augmented, file = output_file_path, sep = "\t", quote = FALSE, row.names = FALSE)

# Verify that the file has been saved
if (file.exists(output_file_path)) {
  cat("Data with selected columns has been saved to", output_file_path, "\n")
} else {
  cat("Failed to save the data with selected columns to", output_file_path, "\n")
}
```
